### ISSUE TITLE
Can't import lintdb

### ISSUE THREAD

**Issue by agoriwmt** [DeployQL/LintDB#25]
Admittedly I have no experience with Conda and I am pretty new to Python. Btw I have installed Conda from scratch, installed lintdb, but a simple import like this fails:

```
>>> import lintdb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/app/lintdb.py", line 6, in <module>
    index = lintdb.IndexIVF(
AttributeError: partially initialized module 'lintdb' has no attribute 'IndexIVF' (most likely due to a circular import)
```

Any clue on what may be wrong?

**Comment by mtbarta** [comment]
what was the issue?

**Comment by agoriwmt** [comment]
I am not sure, it started to work at some point. I think first time I tried

`conda install deployql::lintdb`

and later

`conda install lintdb -c deployql -c conda-forge`

or maybe it's just that I closed and re-opened the terminal.
